### ISSUE TITLE
[QUESTION] About models

### ISSUE THREAD

**Issue by loretoparisi** [jordipons/musicnn#8]
Hello Jordi,
I was looking at the recent [TensorflowPredictMusiCNN](https://essentia.upf.edu/reference/std_TensorflowPredictMusiCNN.html), that's an amazing work, congrats!
In the essentia documentation there are several models linked [here](https://essentia.upf.edu/models/). Is the same musicnn architecture and models when installing it via pip or it has been updated in the essentia repo?

Thank you!

**Comment by jordipons** [comment]
Thanks  for your interest!
I suggest directly asking to Essentia developers (Pablo and Dmitry), who might have the answers to these details!

**Comment by loretoparisi** [comment]
@jordipons thank you Jordi, I did.
